name: Deploy to EC2 (No Docker Hub)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd devops-zero
            git pull origin main

            docker stop devops-zero || true
            docker rm devops-zero || true

            docker build -t devops-zero .
            docker run -d -p 3000:3000 --name devops-zero devops-zero
